### ISSUE TITLE
MDX Support

### ISSUE THREAD

**Issue by aloenobilis** [akanshgulati/gatsby-theme-ghost#8]
Hi, 

First of all thanks for this awesome starter. 
I am trying to get mdx to work,  tried a few times. Would you know  how to enable  support for this?

**Comment by styxlab** [comment]
This repository is mainly intended for sourcing in content from a headless Ghost CMS. However, I do think that you can get MDX files in on separate pages (similar to the 404 page), if you install the required plugins. Could you elaborate a bit on your use case, what do you intend to do and why?

**Comment by akanshgulati** [comment]
Hi
For now it does not have support for it. Will update in future if that can be added.
